<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scala</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Scala</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>/\*\*/</string>
			<key>name</key>
			<string>comment.block.empty.scala</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?/\*\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scsala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/(\s*\n)?</string>
			<key>name</key>
			<string>comment.block.documentation.scala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@(param|return|throws|exception|author|version|see|since|serial|serialField|serialData|deprecated)\b</string>
					<key>name</key>
					<string>keyword.other.documentation.scaladoc.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{@link\s+[^\}]*\}</string>
					<key>name</key>
					<string>keyword.other.documentation.scaladoc.link.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case|else|for|if|return|while|yield)\b</string>
			<key>name</key>
			<string>keyword.control.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(catch|finally|throw|try)\b</string>
			<key>name</key>
			<string>keyword.exception.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|package|requires)\b</string>
			<key>name</key>
			<string>keyword.import.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|class|def|extends|final|implicit|import|sealed|new|object|override|package|private|protected|requires|sealed|trait|type|val|var)\b</string>
			<key>name</key>
			<string>keyword.declarations.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(do|match|new|with)\b</string>
			<key>name</key>
			<string>keyword.misc.scala</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(super|this)\b</string>
			<key>name</key>
			<string>variable.language.scala</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.scala</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.scala</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scala</string>
	<key>uuid</key>
	<string>158C0929-299A-40C8-8D89-316BE0C446E8</string>
</dict>
</plist>
